name: BINGO
model: CPL
description: |
  BINGO single-dish 21cm intensity mapping survey targeting 0.13 < z < 0.5.
  Forecast follows baseline specifications in Abdurashidova et al. (2022).
parameters:
  - H0
  - Omega_m
  - w0
  - wa
reference:
  H0: 67.36
  Omega_m: 0.3153
  Omega_b: 0.0493
  Omega_k: 0.0
  sigma8: 0.8111
  n_s: 0.9649
  T_cmb: 2.7255
  N_eff: 3.046
  w0: -1.0
  wa: 0.0
measurements:
  - z: 0.30
    sigma_da: 0.030
    sigma_h: 0.036
    sigma_fs8: 0.090
  - z: 0.40
    sigma_da: 0.028
    sigma_h: 0.034
    sigma_fs8: 0.085
priors:
  H0: 5.0
survey:
  sky_fraction: 0.1
  time_years: 1.0
  channel_width_mhz: 1.0
  notes: 40 feed horns, dual-dish configuration
