name: CHIME
model: CPL
description: |
  CHIME 21cm intensity mapping survey probing 0.8 < z < 2.5 with cylindrical
  interferometer technology.
parameters:
  - H0
  - Omega_m
  - w0
  - wa
reference:
  H0: 67.36
  Omega_m: 0.3153
  Omega_b: 0.0493
  Omega_k: 0.0
  sigma8: 0.8111
  n_s: 0.9649
  T_cmb: 2.7255
  N_eff: 3.046
  w0: -1.0
  wa: 0.0
measurements:
  - z: 0.90
    sigma_da: 0.022
    sigma_h: 0.028
    sigma_fs8: 0.060
  - z: 1.20
    sigma_da: 0.020
    sigma_h: 0.026
    sigma_fs8: 0.058
  - z: 1.60
    sigma_da: 0.021
    sigma_h: 0.028
    sigma_fs8: 0.060
  - z: 2.00
    sigma_da: 0.025
    sigma_h: 0.032
    sigma_fs8: 0.065
priors:
  H0: 4.5
survey:
  sky_fraction: 0.55
  time_years: 3.0
  channel_width_mhz: 0.39
  notes: Cylindrical array, drift scan at fixed declination
