# SKA1-MID Medium-Deep Band 2 Survey Configuration
# Reference: SKA Red Book 2018, Bull et al. 2016 Table 1
#
# This file contains ONLY hardware specifications and observing strategy.
# Cosmological model parameters (H0, Omega_m, w0, wa, etc.) should be
# specified in analysis scripts, NOT in this configuration file.

name: ska1_mid_band2
description: "SKA1-MID Medium-Deep Band 2 survey (Red Book 2018)"

# Hardware configuration
instrument:
  telescope_type: single_dish
  ndish: 200
  dish_diameter_m: 15.0
  nbeam: 1

# Observing strategy
observing:
  survey_area_deg2: 5000.0
  total_time_hours: 10000.0
  frequency_range_MHz: [950, 1420]
  channel_width_MHz: 0.05
  channel_width_hz: 50000.0  # 50 kHz

# Noise parameters
noise:
  system_temperature_K: 13.5
  sky_temperature:
    model: power_law
    T_ref_K: 25.0
    nu_ref_MHz: 408.0
    beta: 2.75

# HI tracer properties (observational, not cosmological)
hi_tracers:
  bias:
    model: polynomial
    coefficients: [0.67, 0.18, 0.05]
  density:
    model: polynomial
    coefficients: [0.00048, 0.00039, -0.000065]

# Redshift binning strategy
redshift_bins:
  default_delta_z: 0.1
  centers:
    - 0.05
    - 0.15
    - 0.25
    - 0.35
    - 0.45

# Metadata for provenance tracking
metadata:
  reference: "SKA Red Book 2018, Bull et al. 2016 Table 1"
  notes: "Medium-deep survey optimized for 0.0 < z < 0.5"
  date_created: "2025-10-28"
  schema_version: "2.0"
