# SKA1-MID Wide Band 1 Survey Configuration
# Reference: SKA Red Book 2018, Bull et al. 2016 Table 1
#
# This file contains ONLY hardware specifications and observing strategy.
# Cosmological model parameters (H0, Omega_m, w0, wa, etc.) should be
# specified in analysis scripts, NOT in this configuration file.

name: ska1_wide_band1
description: "SKA1-MID Wide Band 1 IM survey (Red Book 2018)"

# Hardware configuration
instrument:
  telescope_type: single_dish
  ndish: 200
  dish_diameter_m: 15.0
  nbeam: 1

# Observing strategy
observing:
  survey_area_deg2: 20000.0
  total_time_hours: 10000.0
  frequency_range_MHz: [350, 1050]
  channel_width_MHz: 0.05
  channel_width_hz: 50000.0  # 50 kHz

# Noise parameters
noise:
  system_temperature_K: 25.0
  sky_temperature:
    model: power_law
    T_ref_K: 25.0
    nu_ref_MHz: 408.0
    beta: 2.75

# HI tracer properties (observational, not cosmological)
hi_tracers:
  bias:
    model: polynomial
    coefficients: [0.67, 0.18, 0.05]
  density:
    model: polynomial
    coefficients: [0.00048, 0.00039, -0.000065]

# Redshift binning strategy
redshift_bins:
  default_delta_z: 0.1
  centers:
    - 0.35
    - 0.45
    - 0.55
    - 0.65
    - 0.75
    - 0.85
    - 0.95
    - 1.05
    - 1.15
    - 1.25
    - 1.35
    - 1.45
    - 1.55
    - 1.65
    - 1.75
    - 1.85
    - 1.95
    - 2.05
    - 2.15
    - 2.25
    - 2.35
    - 2.45
    - 2.55
    - 2.65
    - 2.75
    - 2.85
    - 2.95

# Metadata for provenance tracking
metadata:
  reference: "SKA Red Book 2018, Bull et al. 2016 Table 1"
  notes: "Wide survey optimized for 0.35 < z < 3.0"
  date_created: "2025-10-28"
  schema_version: "2.0"
