name: SKA_MID
model: CPL
description: |
  SKA Phase 1 MID intensity mapping survey with single-dish mode covering
  0.2 < z < 2.5. Forecast numbers follow Bull et al. (2015) benchmark scenario.
parameters:
  - H0
  - Omega_m
  - w0
  - wa
reference:
  H0: 67.36
  Omega_m: 0.3153
  Omega_b: 0.0493
  Omega_k: 0.0
  sigma8: 0.8111
  n_s: 0.9649
  T_cmb: 2.7255
  N_eff: 3.046
  w0: -1.0
  wa: 0.0
measurements:
  - z: 0.30
    sigma_da: 0.015
    sigma_h: 0.018
    sigma_fs8: 0.050
  - z: 0.60
    sigma_da: 0.012
    sigma_h: 0.016
    sigma_fs8: 0.045
  - z: 1.00
    sigma_da: 0.011
    sigma_h: 0.015
    sigma_fs8: 0.042
  - z: 1.50
    sigma_da: 0.012
    sigma_h: 0.018
    sigma_fs8: 0.048
  - z: 2.00
    sigma_da: 0.016
    sigma_h: 0.022
    sigma_fs8: 0.060
priors:
  H0: 4.0
  Omega_m: 0.03
survey:
  sky_fraction: 0.75
  time_years: 2.0
  channel_width_mhz: 0.35
  notes: 190 dish receivers, 1.7 sr coverage
